# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9213bc28f1d3263acbf37aee2a0aca72b0dd3249347fe0d8049fd7d19ebfc67f70d7d8dce3afe7dd3a306579605444ceae2bf8720c0216113a1da2fbcadaa11

test:
  secret_key_base: 2455667554ef903446284a99305c702424e2f93e30dbeac4b2532a1e598f90f294d20ada214b33a469e9dbe6618ce5850de99b3d7a4a1e8ce9aee936c58d40a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
